export interface Participant {
    record_id?: number,
    redcap_repeat_instrument?: string,
    redcap_repeat_instance?: number,

    f645_firstname?: string,
    f645_lastname?: string,
    f645_zerodate?: string,
    dispositivo?: string,
    email?: string,
    f645_code?: string,
    f645_joindate?: string,
    f645_pushids?: string,

    participantes_complete?: number,
}

export interface BaselineData {
    record_id?: number,

    sexo?: string,
    edad?: string,
    e_civil?: string,
    enf_previas___1?: string,
    enf_previas___2?: string,
    enf_previas___3?: string,
    enf_previas___4?: string,
    enf_previas___5?: string,
    enf_previas___6?: string,
    enf_previas___7?: string,
    enf_previas___8?: string,
    enf_previas___9?: string,
    enf_previas___10?: string,
    enf_previas___11?: string,
    enf_previas___12?: string,
    enf_previas___13?: string,
    enf_previas___14?: string,
    enf_previas___15?: string,
    cancer_ta?: string,
    estadio_erc?: string,
    otros?: string,
    ocd?: string,
    caidas?: string,
    gds?: string,
    ub_basal?: string,
    ay_basal?: string,
    f_basales?: string,
    f_basales_tipo___1?: string,
    f_basales_tipo___2?: string,
    f_basales_tipo___3?: string,
    op_basales___0?: string,
    op_basales___1?: string,
    op_basales___2?: string,
    op_basales___3?: string,
    op_basales___4?: string,
    op_basales___5?: string,
    op_basales___6?: string,
    f_ingreso?: string,
    f_cirug_a?: string,
    tipo_fractura?: string,
    fx_asociada?: string,
    tipo_cirugia?: string,
    asa?: string,
    ret_qx?: string,
    motivo_ret_qx?: string,
    compl_intrahosp?: string,
    compl_intrahosp_tipo___1?: string,
    compl_intrahosp_tipo___2?: string,
    compl_intrahosp_tipo___3?: string,
    compl_intrahosp_tipo___4?: string,
    compl_intrahosp_tipo___5?: string,
    compl_intrahosp_tipo___6?: string,
    compl_intrahosp_tipo___7?: string,
    compl_intrahosp_tipo___8?: string,
    compl_intrahosp_tipo___9?: string,
    compl_intrahosp_tipo___10?: string,
    compl_intrahosp_tipo___11?: string,
    comp_intrahosp_otras?: string,
    carga_alta?: string,
    destino_alta?: string,
    causa_exitus_intrahosp?: string,
    rehab_alta?: string,
    comentarios?: string,

    datos_basales_complete?: number
}

